from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, TextAreaField, IntegerField, FileField, SelectField, widgets, BooleanField, RadioField
from wtforms.validators import InputRequired, Length, Regexp, Required

class CreateUserForm(FlaskForm):
	firstname 		= StringField('First Name', validators 		= [ InputRequired()], render_kw = {'placeholder' : 'First Name'})
	lastname 		= StringField('Last Name', 	validators 		= [ InputRequired()], render_kw = { 'placeholder' : 'Last Name'})
	username 		= StringField('Username', 	validators 		= [ InputRequired(),Length(min = 8, max = 200) ], render_kw = {'placeholder' : 'Username'})
	age 			= IntegerField('Age', 		validators 		= [ InputRequired()], render_kw = {'placeholder' : 'Age'})
	gender 			= SelectField('Gender Type',choices 		= [('1','FEMALE'), ('2','MALE')], default = '2')
	height          = SelectField('Height',     choices 		= [('1','Tall'), ('2','Medium'), ('3','Short')], default = '3')
	country         = StringField('Current Address', validators = [ InputRequired()], render_kw = { 'placeholder' : 'Current Address'})
	origin          = StringField('Country of Origin', validators = [ InputRequired()], render_kw = { 'placeholder' : 'Country of Origin'})
	professional    = SelectField("Professional skill level", choices = [('1', 'Unskilled'), ('2', 'Skilled'), ('3', 'Technical'), ('4', 'Professional')], default = '4')
	school          = SelectField("Last School Attended", choices = [('1', 'Primary'), ('2', 'Secondary'), ('3', 'Tertiary'), ('4', 'Post Graduate')], default = '4')
	userrel         = SelectField("Are you religiously affiliated?", choices = [('1', 'Yes'), ('2', 'No')], default = '2')
	userrelty       = SelectField("If yes, which Religion?", choices = [('1', 'Christianity'), ('2', 'Judaism'), ('3', 'Islam'), ('4', 'Other')], default = '4')
	honesty			= BooleanField('Honesty')
	friendly		= BooleanField('Friendly')
	loyalty			= BooleanField('Loyalty')
	integrity       = BooleanField('Integrity')
	respectful      = BooleanField('Restpectful')
	compassionate   = BooleanField('Compassionate')
	fair            = BooleanField('Fair')
	forgiving       = BooleanField('Forgiving')
	courageous      = BooleanField('Courageous')
	generous        = BooleanField('Generous')
	polite          = BooleanField('Polite')
	kind            = BooleanField('Kind')
	loving          = BooleanField('Loving')
	optimistic      = BooleanField('Optimistic')
	reliable        = BooleanField('Reliable')
	conscious       = BooleanField('Conscious')
	password 		= PasswordField('Password', validators 		= [ InputRequired() ] , render_kw = {'placeholder' : 'Password'})
	image 			= FileField('Image File', 	validators 		= [ Regexp(u'^[^/\\\\]\.$'), InputRequired() ])
	bio 			= TextAreaField('BIO', 		validators 		= [ InputRequired(), Length(max = 200) ], render_kw = {'placeholder' : 'A short bio....', 'rows' : '5'})

class ProfileInfo(FlaskForm):	
	f               = SelectField("What gender are you interested in?", choices = [('1','FEMALE'), ('2','MALE')], default = '2') 
	c               = SelectField("What height are you interested in?", choices = [('1', 'Tall'), ('2', 'Medium'), ('3', 'Short')], default = '3')
	r               = SelectField("Would you like your partner to be religiously affiliated?", choices = [('1', 'Yes'), ('2', 'No')], default = '2')
	r1              = SelectField("If yes, which Religion?", choices = [('1', 'Christianity'), ('2', 'Judaism'), ('3', 'Islam'), ('4', 'Other')], default = '4')
	a               = IntegerField("What age partner do you seek?", validators    = [ InputRequired()], render_kw = {'placeholder' : 'Age'})
	honesty			= BooleanField('Honesty')
	friendly		= BooleanField('Friendly')
	loyalty			= BooleanField('Loyalty')
	integrity       = BooleanField('Integrity')
	respectful      = BooleanField('Restpectful')
	compassionate   = BooleanField('Compassionate')
	fair            = BooleanField('Fair')
	forgiving       = BooleanField('Forgiving')
	courageous      = BooleanField('Courageous')
	generous        = BooleanField('Generous')
	polite          = BooleanField('Polite')
	kind            = BooleanField('Kind')
	loving          = BooleanField('Loving')
	optimistic      = BooleanField('Optimistic')
	reliable        = BooleanField('Reliable')
	conscious       = BooleanField('Conscious')
	
	traveling	    = BooleanField('Traveling')
	food		    = BooleanField('Food')
	sports			= BooleanField('Sports')
	movies          = BooleanField('Movies')
	exercising      = BooleanField('Exercising')
	shopping        = BooleanField('Shopping')
	music           = BooleanField('Music')
	singing         = BooleanField('Singing')
	dancing         = BooleanField('Dancing')
	reading         = BooleanField('Reading')
	fashion         = BooleanField('Fashion')
	pets            = BooleanField('Pets')
	
	
	